- Elgato Systems GmbH/Elgato Video Capture.download.recipe
This will use a valid version number ("x.x.x") instead of the invalid version number ("x.x.x (xxxx)") that is inside the application, allowing the pkg_request processor in the .pkg recipe to run successfully.
> Swapped out versioner for a scrap of the Sparkle feed

- SketchupMake/SketchUpMake.download.recipe
The text on the download webpage no longer has ".dmg" at the end of it.
It instead has "-dmg" (e.g. "sketchupmake-2017-3-116-90853-fr-dmg").
This causes recipes that act on the .dmg to fail. Giving URLDownloader
a file name allows the recipe to succeed.
> Adding a "filename" to URLDownloader

- Mattermost/Mattermost.munki.recipe
Mattermost is no longer distributed as an archive but as a dmg.
> Mattermost is no longer distributed as an archive.

- Mattermost/Mattermost.munki.recipe
Because Mattermost is downloaded as dmg, we dont need DmgCreator anymore.
> Mattermost is distributed as an dmg now.

- Composer/PHPComposerURLProvider.py
- GitCommitAndPush/GitCommitAndPush.py
- GitFatCommitAndPush/GitFatCommitAndPush.py
- MunkiNormalizePath/MunkiNormalizePath.py
- RunSyncCommand/RunSyncCommand.py
In order to make your processors more compatible with AutoPkg running in Python 3, I've applied a few adjustments suggested by `python-modernize`, `pylint --py3k`, and `pylint` in general.
More adjustments may need to be made manually later (including `urlparse` and `HTMLParser` in PHPComposerURLProvider), but this should catch the low-hanging fruit right now.
> Basic python3 compatibility

- CNIL/PIA.install.recipe
- CNIL/PIA.pkg.recipe
- Elgato Systems GmbH/Elgato Video Capture.install.recipe
- Elgato Systems GmbH/Elgato Video Capture.pkg.recipe
- Krystof Vasa/Downie.download.recipe
- Krystof Vasa/Downie.install.recipe
- Techno-Grafik Christian Lackner eU/iTaskX3.download.recipe
- Techno-Grafik Christian Lackner eU/iTaskX3.install.recipe
- Texpad/Texpad.download.recipe
- Texpad/Texpad.install.recipe
- Texpad/Texpad.pkg.recipe
- Texpad/TexpadBeta.download.recipe
- Texpad/TexpadBeta.install.recipe
- Texpad/TexpadBeta.pkg.recipe
Because variables can be overridden, it's a good idea to make sure that the recipe will still work even if a non-default variables used. One issue that would prevent recipes from running is using a `NAME` variable in paths that should be hard-coded (e.g. `/Applications/Foo.app`).
This PR removes the `NAME` variable from all file paths and replaces it with the actual app name, which should make the recipe more resilient for overrides.
> Remove NAME variable from app paths

- Terminus/Terminus.download.recipe
Detected and changed HTTPS URLs automatically using my [HTTPS Spotter](https://www.elliotjordan.com/posts/autopkg-https/) script, and then tested all changed recipes manually to ensure download success.
> Update all available URLs from HTTP to HTTPS

- Composer/PHPComposer.pkg.recipe
- Elasticsearch/Elasticsearch.pkg.recipe
- SketchupMake/SketchUpMake.pkg.recipe
`pkgname` is [intended](https://github.com/autopkg/autopkg/blob/e36d5cba2823dbdfcb69a41a38b1aef9fb76121c/Code/autopkgserver/autopkgserver#L47) to be in the `pkg_request` dictionary, not as a standalone argument for [PkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-PkgCreator).
> Adjust PkgCreator arguments

- Postico/Postico.pkg.recipe
This pull request removes unused instances of `BUNDLE_ID` from recipe input variables, which will help reduce confusion by new AutoPkg users and simplify overrides created from this point on.
Making `BUNDLE_ID` available as an input variable is a common practice in AutoPkg recipes that use the [PkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-PkgCreator) processor ([example](https://github.com/autopkg/homebysix-recipes/blob/4fec9244a3af0f9b7c8f61f35a5cd7f4622fb162/soma-zone/LaunchControl.pkg.recipe#L40-L41)). It's likely that these recipes transitioned from PkgCreator to the more streamlined [AppPkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-AppPkgCreator) processor some time ago, but the now-unused input variable for `BUNDLE_ID` was never removed.
Because an …
> Remove unused BUNDLE_ID input var

- Termius/Termius.download.recipe
- Termius/Termius.munki.recipe
Should be Termius and not Terminus.
Not sure if you want to handle this gracefully, or not.
Gracefully would be to have recipes with the same terminus identifiers as now.. but with https://github.com/autopkg/autopkg/wiki/Processor-DeprecationWarning point to the correctly named recipes.
Or.. not at all :)
> Correct Termius recipes

- PaloAlto/GlobalProtectMac.munki.recipe
GlobalProtect version number always was 0.0 ... these Changes will pass through the version number and GlobalProtect will import to munch with the correct version number.
> Fix GlobalProtect Version number munkiimport

- GitCommitAndPush/GitCommitAndPush.py
- GitFatCommitAndPush/GitFatCommitAndPush.py
- MunkiNormalizePath/MunkiNormalizePath.py
- RunSyncCommand/RunSyncCommand.py
As of macOS Monterey 12.3, the version of Python 2 that shipped with macOS located at `/usr/bin/python` [has been removed](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). More context can be found in some posts from Mac admins at the beginning of 2022, aggregated [here](https://scriptingosx.com/2022/03/macos-monterey-12-3-removes-python-2-link-collection/).
Since [version 2.0.2](https://github.com/autopkg/autopkg/releases/tag/v2.0.2), AutoPkg's installer has included its own Python 3 framework, symlinked from `/usr/local/autopkg/python`. This pull request adjusts the "shebang" interpreter paths of processors to replace `/usr/bin/env python` with the AutoPkg Python 3 path.
NOTE: Because AutoPkg processors are imported as modules by AutoPkg and not …
> Update Python path in processors to reflect changes in macOS 12.3+

- Mattermost/Mattermost.download.recipe
Release 5.x now includes an architecture suffix for macos DMGs. I propose to use the universal dmg. Not sure how this is supposed to work for non-mac use cases however. But then, they are broken because of the `.dmg` ending anyway.
> Mattermost: Fix regex and use new universal dmg

- AWS VPN Client/AWS VPN Client.munki.recipe
Hi, @ygini 
The AWS VPN Client Munki recipe currently doesn't set the `minimum_os_version` from the App's info.plist, and as such a default value of 10.5.0 is being set.
This PR adds in support for the new `derive_minimum_os_version` key in the `MunkiInstallsItemsCreator` processor. With this set the min_os_version becomes 10.10
This change requires AutoPkg version 2.7 or higher, if compatibility with older versions of AutoPkg is needed, the same result could be achieved with something like below.
```
<dict>
<key>Arguments</key>
<dict>
<key>info_path</key>
<string>%RECIPE_CACHE_DIR%/Applications/APP_NAME.app</string>
<key>plist_keys</key>
<dict>
<key>LSMinimumSystemVersion</key>
<string>min_os_ver</string>
</dict>
</dict>
<key>Processor</key>
<string>PlistReader</string>
</dict>
<dict> …
```
> Update AWS VPN Client.munki.recipe

- AWS VPN Client/AWS VPN Client.download.recipe
Changes download to scrape - https://docs.aws.amazon.com/vpn/latest/clientvpn-user/client-vpn-connect-macos-release-notes.html.
Before this change this recipe was downloading a prior release (3.10)
> Update AWS VPN Client.download.recipe

- SketchupMake/SketchUpMake.download.recipe
This PR deprecates the SketchUp Make recipes, since that software is no longer available to download ([details](https://help.sketchup.com/en/make-access)).
> Deprecate SketchUp Make recipes

- WS1UEMAgent/WS1UEMAgent.download.recipe
This PR deprecates the non-functional WorkSpace ONE UEM Agent recipes and points users to an alternative in the hjuutilainen-recipes repo.
> Deprecate WorkSpace ONE UEM Agent recipes

- CounterPath/X-Lite.download.recipe
This PR deprecates the X-Lite recipes, since this software has been rebranded as Bria, and points users to an alternative recipe in the dataJAR-recipes repo.
> Deprecate X-Lite recipes

- Elgato Systems GmbH/Elgato Video Capture.download.recipe
- Elgato Systems GmbH/Elgato Video Capture.install.recipe
- Elgato Systems GmbH/Elgato Video Capture.munki.recipe
- Elgato Systems GmbH/Elgato Video Capture.pkg.recipe
This PR reworks the Elgato Video Capture recipes because the old Sparkle feed is now offline. Instead, we use URLTextSearcher to determine the latest version's download URL. The download is now in zip format, so child recipes needed adjustment for that change.
Verbose recipe run output for download, munki, and pkg recipes:
```
% autopkg run -vv Elgato\ Video\ Capture.{download,pkg,munki}.recipe
Processing Elgato Video Capture.download.recipe...
WARNING: Elgato Video Capture.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': 'href="(https://edge\\.elgato\\.com/video-capture/macos/[\\d\\.]+/Video_Capture_(?P<version>[\\d\\.]+)\\.zip)"',
'request_headers': {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel ' …
```
> Fix Elgato Video Capture recipes

- FileMaker14/FileMaker14Updater.download.recipe
- FileMaker15/FileMaker15Updater.download.recipe
- FileMaker16/FileMaker16Updater.download.recipe
This PR deprecates end-of-life FileMaker download recipes. Details to Claris support announcements are provided in the deprecation warning message.
> Deprecate FileMaker recipes

- Techno-Grafik Christian Lackner eU/iTaskX3.download.recipe
This PR deprecates the iTaskX 3 recipes, since the software is no longer available to download. Users are directed to working iTaskX 4 recipes in the andredb90-recipes or zentral-recipes repos.
> Deprecate iTaskX 3 recipes

- NoMachine/NoMachine.download.recipe
- NoMachine/NoMachine.munki.recipe
This PR deprecates the non-functional NoMachine.download recipe, and switches the NoMachine.munki parent recipe to a working equivalent in novaksam-recipes.
Verbose munki recipe run output:
```
% autopkg run -vvq NoMachine.munki.recipe
Processing NoMachine.munki.recipe...
WARNING: NoMachine.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'curl_opts': ['-b nomachine_cookies.txt -L'],
're_pattern': '(https://.*nomachine_[0-9\\.\\_]+.dmg)',
'url': 'https://downloads.nomachine.com/download/?id=7'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Found matching text (match): https://download.nomachine.com/download/8.14/MacOSX/nomachine_8.14.2_4.dmg …
```
> Deprecate NoMachine.download and give NoMachine.munki a working parent
